---
- name: Disable mouse pointer hiding
  when: disable_mouse_pointer_hiding
  ansible.windows.win_regedit:
    path: HKCU:\Control Panel\Desktop
    name: UserPreferencesMask
    data: [0x9e, 0x1e, 0x06, 0x80, 0x12, 0x00, 0x00, 0x00]
    type: binary

- name: Disable Xbox Game Bar and Game DVR
  when: disable_game_bar
  ansible.windows.win_regedit:
    path: HKLM:\SOFTWARE\Policies\Microsoft\Windows\GameDVR
    name: AllowgameDVR
    data: 0
    type: dword

- name: Disable screen saver
  when: disable_screensaver
  ansible.windows.win_regedit:
    path: HKCU:\Control Panel\Desktop
    name: ScreenSaveActive
    data: 0
    type: dword

- name: Disable display timeout
  when: disable_display_timeout
  ansible.windows.win_shell: |
    powercfg -x -monitor-timeout-ac 0
    powercfg -x -monitor-timeout-dc 0

- name: Disable keyboard accessibility features
  when: disable_keyboard_accessibility
  ansible.windows.win_regedit:
    path: HKCU:\Control Panel\Accessibility\{{ feature.name }}
    name: Flags
    data: "{{ feature.value }}"
    type: dword
  loop:
    - name: StickyKeys
      value: 506
    - name: Keyboard Response
      value: 122
    - name: ToggleKeys
      value: 58
  loop_control:
    loop_var: feature

- name: Disable Edge desktop shortcut on new profiles
  when: disable_edge_shortcut
  ansible.windows.win_regedit:
    path: HKLM:\Software\Microsoft\Windows\CurrentVersion\Explorer
    name: DisableEdgeDesktopShortcutCreation
    data: 1
    type: dword

- name: Restore old volume slider
  when: restore_old_volume_slider
  ansible.windows.win_regedit:
    path: HKLM:\Software\Microsoft\Windows\CurrentVersion\MTCUVC
    name: EnableMtcUvc
    data: 0
    type: dword

- name: Disable Aero-Shake Minimize feature
  when: disable_aero_shake
  ansible.windows.win_regedit:
    path: HKCU:\SOFTWARE\Microsoft\Windows\CurrentVersion\Explorer\Advanced
    name: DisallowShaking
    data: 1
    type: dword

- name: Set Explorer as default view for This PC
  when: set_explorer_default_this_pc
  ansible.windows.win_regedit:
    path: HKCU:\SOFTWARE\Microsoft\Windows\CurrentVersion\Explorer\Advanced
    name: LaunchTo
    data: 1
    type: dword

- name: Set better folder view options
  when: set_folder_view_options
  ansible.windows.win_regedit:
    path: HKCU:\SOFTWARE\Microsoft\Windows\CurrentVersion\Explorer\Advanced
    name: "{{ feature.name }}"
    data: "{{ feature.value }}"
    type: dword
  loop:
    - name: Hidden
      value: 1
    - name: HideFileExt
      value: 0
    - name: HideDrivesWithNoMedia
      value: 0
    - name: ShowSyncProviderNotifications
      value: 0
  loop_control:
    loop_var: feature

- name: Enable Command Prompt QuickEdit mode
  when: enable_quickedit
  ansible.windows.win_regedit:
    path: HKCU:\Console
    name: QuickEdit
    value: 1
    type: dword

- name: Show Run in Start menu
  when: show_run
  ansible.windows.win_regedit:
    path: HKCU:\SOFTWARE\Microsoft\Windows\CurrentVersion\Explorer\Advanced
    name: Start_ShowRun
    value: 1
    type: dword

- name: Show Admin Tools in Start menu
  when: show_admin_tools
  ansible.windows.win_regedit:
    path: HKCU:\SOFTWARE\Microsoft\Windows\CurrentVersion\Explorer\Advanced
    name: StartMenuAdminTools
    value: 1
    type: dword

- name: Remove library folders from This PC (64-bit)
  ansible.windows.win_regedit:
    path: HKLM:\SOFTWARE\Microsoft\Windows\CurrentVersion\Explorer\MyComputer\NameSpace
    name: "{{ folder }}"
    state: absent
  loop: "{{ library_folders }}"
  loop_control:
    loop_var: folder

- name: Remove library folders from This PC (32-bit)
  ansible.windows.win_regedit:
    path: HKLM:\SOFTWARE\Wow6432Node\Microsoft\Windows\CurrentVersion\Explorer\MyComputer\NameSpace\
    name: "{{ folder }}"
    state: absent
  loop: "{{ library_folders }}"
  loop_control:
    loop_var: folder
